// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PauseDownload(arg1:string):Promise<void>;

export function ResumeDownload(arg1:string):Promise<void>;

export function StartDownload(arg1:string,arg2:string):Promise<string>;
